### ISSUE TITLE
Suggestion - add IDs to each section and link in nav

### ISSUE THREAD

**Issue by jzhu01** [Ragee23/Ragee23.github.io#1]
Seen here: https://github.com/Ragee23/Ragee23.github.io/blob/5332c84529b47d96442912befadf0154448c4aa7/index.html#L12-L14
It might be nice to add IDs to each section and then link those in the nav. Here’s a useful reference: https://www.w3.org/TR/html4/struct/links.html!

**Comment by Ragee23** [comment]
Oh I remember "linking" earlier in this course and w3.org is still a mess for me to navigate, would you be able to give me one example?

**Comment by jzhu01** [comment]
Sure! So you could do something like: 
```
 <span><a href="#mission">Mission</a></span> 
``` 
and then later on have: 
```
<div id="mission"> additional code here </div> 
```
Sorry for the delay, and I hope this helps!
